Repository Muneerali199/DocMagic, pull requests merged in 2025-08, with the labels that each got.

#279 Enhanced the features section at home page and made it engaging
  app/globals.css
  app/page.tsx
Labels: enhancement, gssoc 25, level 2, feature

#86 Fixes #75: Add badges for build, license, and dependencies
  README.md
Labels: good first issue, gssoc 25, level 1

#281 gssoc/added testimonials-slider
  components/testimonials-section.tsx
Labels: enhancement, gssoc 25, level 2, feature

#280 fix: This PR resolves a crash that occurred when navigating back to the /settings page.
  lib/supabase/client.ts
Labels: bug, enhancement, gssoc 25, level 2

#291 feat: Add 10 new templates for CVs, resumes,presentations and letters
  templates/cv/Marketing_Manager_cv.md
  templates/cv/Marketing_Specialist_cv.md
  templates/cv/Medical_Professional_cv.md
  templates/letter/Letter Of Resignation.md
  templates/letter/Letter of Recommendation.md
  templates/letter/Professional_newletter.md
  templates/presentation/Business_case_study.md
  templates/presentation/Work_summary.md
  templates/resume/Full stack devoloper_resume.md
  templates/resume/Sales_Representative_resume.md
Labels: gssoc 25, level 3

#289 Create SETUP_WINDOWS.md
  SETUP_WINDOWS.md
Labels: good first issue, gssoc 25, level 1

#299 Fixed Mail issue in ui .
  app/auth/register/page.tsx
  app/auth/signin/page.tsx
  app/contact/page.tsx
  components/letter/letter-generator.tsx
  components/resume/guided-resume-generator.tsx
  components/resume/resume-generator.tsx
  lib/validation.ts
Labels: enhancement, gssoc 25, level 2

#310 fix: add accessible ScrollToTop button with theme support and glassm…
  components/scroll-to-top.tsx
Labels: enhancement, good first issue, gssoc 25, level 1

#341 fix: added hover effects to Customer Love and Social Proof components…
  components/testimonials-section.tsx
  package-lock.json
Labels: good first issue, osci 25, 1⭐
